#!/usr/bin/env make -f

###############################################################################@
#
# @BEGIN
#
# @COPYRIGHT BEGIN
# Copyright (C) 2020 Panos I. Papadopoulos <panos1962_AT_gmail_DOT_com>
# @COPYRIGHT END
#
# @FILETYPE BEGIN
# makefile
# @FILETYPE END
#
# @FILE BEGIN
# www/checkin/Makefile —— Makefile
# @FILE END
#
# @HISTORY BEGIN
# Created: 2024-03-22
# @HISTORY END
#
# @END
#
###############################################################################@

test:
	@:
